make assignment of contains Or stick in query builder
helibproject/HElib pull request #14
Opened 2022-06-24 09:58 UTC by TabOg

Make containsOR flag stick once true. Initialised to false on line 431

2022-06-27 16:47 UTC, hamishun requested changes
Should we add some test, to test this issue appearing?

2022-06-28 18:10 UTC, jlhcrawford commented
> Should we add some test, to test this issue appearing?

We probably should test more complex queries like this.

2022-07-11 15:22 UTC, jlhcrawford approved these changes

2022-07-14 15:07 UTC, hamishun approved these changes

2022-07-14 15:07 UTC, faberga approved these changes

2022-07-14 15:09 UTC, merged