Queryambiguous or fix
helibproject/HElib pull request #16
Opened 2022-07-05 13:01 UTC by TabOg

2022-07-12 15:00 UTC, jlhcrawford requested changes

2022-07-12 15:00 UTC, jlhcrawford commented on include/helib/partialMatch.h
> + * @brief A class for holding a shared pointer to an `Expr` object.
```suggestion
 * @brief A class wrapping a shared pointer to an `Expr` object.
```

2022-07-12 15:00 UTC, jlhcrawford commented on include/helib/partialMatch.h
> +  QueryExpr(std::shared_ptr<Expr> p) : exp(p) {}
Doxygen comment for this constructor is missing.

2022-07-12 15:00 UTC, jlhcrawford commented on tests/TestPartialMatch.cpp
> +  }
```suggestion
  {}
```

2022-07-12 15:00 UTC, jlhcrawford commented on tests/TestPartialMatch.cpp
> +  std::vector<std::vector<std::vector<long>>> expected_Fs_vector(6);
Save the hardcoded value of 6 to a variable called `cases` or something. That way there's only one place to change it.

2022-07-12 15:00 UTC, jlhcrawford commented on tests/TestPartialMatch.cpp
> +  for (int j = 0; j < 6; j++) {
Change the 6 to the variable name you chose mentioned above.

2022-07-12 15:00 UTC, jlhcrawford commented on tests/TestPartialMatch.cpp
> +  for (int j = 0; j < 6; j++) {
Also should we check the sizes of expected_{Fs,taus,mus}_vector are the same?

2022-07-14 13:49 UTC, jlhcrawford approved these changes, later dismissed

2022-07-21 15:15 UTC, jlhcrawford requested changes

2022-07-21 15:15 UTC, jlhcrawford commented on include/helib/partialMatch.h
> + * @brief Utility function for creating a  QueryExpr for a specified column
```suggestion
 * @brief Utility function for creating a `QueryExpr` for a specified column
```

2022-07-21 15:15 UTC, jlhcrawford commented on include/helib/partialMatch.h
> + * @return QueryExpr with the specified `ColNumber` as the Expr.
```suggestion
 * @return `QueryExpr` with the specified `ColNumber` as the `Expr`.
```

2022-07-21 15:15 UTC, jlhcrawford commented on include/helib/partialMatch.h
> + * @return QueryExpr with the `AND` as the Expr.
```suggestion
 * @return `QueryExpr` with the `AND` as the `Expr`.
```

2022-07-21 15:15 UTC, jlhcrawford commented on include/helib/partialMatch.h
> + * @return `QueryExpr` with the OR as the Expr.
```suggestion
 * @return `QueryExpr` with the OR as the `Expr`.
```

2022-07-21 15:15 UTC, jlhcrawford commented on misc/psi/lookup/lookup.cpp
> +  helib::QueryBuilder qbExpand((a && b) || c);
```suggestion
  helib::QueryBuilder qbExpand(a || (b && c));
```

2022-07-21 15:18 UTC, jlhcrawford requested changes

2022-07-21 15:18 UTC, jlhcrawford commented on include/helib/partialMatch.h
> +   * @param p The shared pointer to wrap into a QueryExpr
```suggestion
   * @param p The `std::shared_ptr` to wrap into a `QueryExpr`.
```

2022-07-21 15:20 UTC, jlhcrawford approved these changes

2022-07-21 16:06 UTC, faberga approved these changes

2022-07-21 16:12 UTC, merged