Map to01speedup
helibproject/HElib pull request #22
Opened 2022-09-15 10:46 UTC by TabOg

Optimize the function which maps only non zero elements to 1, and zero elements to 0, by implementing an alternative algorithm which takes O(logd) Frobenius automorphisms rather than O(d).

2022-09-26 12:41 UTC, hamishun requested changes

2022-09-26 12:41 UTC, hamishun commented on src/eqtesting.cpp
> +#include <NTL/BasicThreadPool.h>
Just need to add intel copyright contribution similar to previous PRs

2022-09-27 14:46 UTC, jlhcrawford requested changes

2022-09-27 14:46 UTC, jlhcrawford commented on src/eqtesting.cpp
> + * Contributions include *
```suggestion
 * Contributions include
```

2022-09-27 14:46 UTC, jlhcrawford commented on src/eqtesting.cpp
> + *     added an additional optional argument multithread which determines
```suggestion
 *     added an additional optional argument `multithread` which determines 
```

2022-09-28 19:16 UTC, jlhcrawford approved these changes

2022-09-29 14:58 UTC, hamishun approved these changes

2022-10-04 18:12 UTC, faberga approved these changes

2022-10-04 18:15 UTC, merged