Adding a version.{h,cpp}
helibproject/HElib pull request #3
Opened 2020-09-03 14:07 UTC by hamishun

- Simple compile time version to headers.
- Generated by cmake - so one less place to update.
- Also embbed version in the compiled library in case one needs sanity check.

2020-09-04 10:20 UTC, esteffin requested changes

2020-09-04 10:20 UTC, esteffin commented on .gitignore
> +src/version.cpp
```suggestion
```
Not required anymore

2020-09-04 10:20 UTC, esteffin commented on .gitignore
> +# Files generated by templates
```suggestion
```
Not required anymore

2020-09-04 10:20 UTC, esteffin commented on .gitignore
> +include/helib/version.h
```suggestion
```
Not required anymore

2020-09-04 10:20 UTC, esteffin commented on .gitignore
> +test/TestVersion.cpp
```suggestion
```
Not required anymore

2020-09-04 10:20 UTC, esteffin commented on .gitignore
> +
```suggestion
```
Not required anymore

2020-09-04 10:20 UTC, esteffin commented on include/helib/version.in.h
> +  static inline constexpr bool minimum(long major_,
Being a comparison function I suggest to rename it name to `compare` or `greater_equals` or `compatible`, as `minimum` sounds like the `minimal` version required for something.

2020-09-04 10:20 UTC, esteffin commented on include/helib/version.in.h
> +  // clang-format off
Why there is need to switch the formatter off?

2020-09-04 10:20 UTC, esteffin commented on include/helib/version.in.h
> +  // clang-format on
Why there is need to switch the formatter off?

2020-09-04 10:20 UTC, esteffin commented on include/helib/version.in.h
> +   * @return `true` if current HElib version is equal to or more than specified
```suggestion
   * @return `true` if current HElib version is greater or equal than specified
```

2020-09-04 10:20 UTC, esteffin commented on include/helib/version.in.h
> +   * @brief Check the string version from the HElib compiled library instead of
```suggestion
   * @brief Get the string version from the HElib compiled library instead of
```

2020-09-04 10:20 UTC, esteffin commented on include/helib/version.in.h
> +   * the header.
```suggestion
   * the one defined in the header.
```

2020-09-04 10:20 UTC, esteffin commented on include/helib/version.in.h
> +   * @return A string representing the version of HElib in the compiled library
```suggestion
   * @return A string representing the version of HElib stored in the compiled library
```

2020-09-04 10:20 UTC, esteffin commented on include/helib/version.in.h
> +   * instead of from the header.
```suggestion
   * instead of from the one defined in the header.
```

2020-09-04 10:20 UTC, esteffin commented on src/version.in.cpp
> +// This will be in the compiled library.
```suggestion
// This is stored in the compiled library.
```

2020-09-04 10:24 UTC, hamishun commented on include/helib/version.in.h
> +  // clang-format off
Formatter formats the placeholder itself, yikes.

2020-09-04 10:40 UTC, hamishun commented on include/helib/version.in.h
> +  static inline constexpr bool minimum(long major_,
It will be changed

2020-09-04 11:04 UTC, esteffin approved these changes

2020-09-04 12:34 UTC, jlhcrawford commented on include/helib/version.in.h
> +   *specified version version.
```suggestion
   * specified version version.
```

2020-09-04 12:34 UTC, jlhcrawford commented on include/helib/version.in.h
> +   *library instead of from the one defined in the header.
```suggestion
   * library instead of from the one defined in the header.
```

2020-09-04 12:36 UTC, jlhcrawford approved these changes

2020-09-07 19:55 UTC, faberga commented
Let's wait for the tests before merging into master.

2020-09-11 23:44 UTC, faberga approved these changes
Travis build & tests PASSED
Approved

2020-09-11 23:52 UTC, merged