Context builder
helibproject/HElib pull request #30
Opened 2020-10-08 10:16 UTC by jlhcrawford

Context builder class taking the responsiblity for constructing both BGV and CKKS contexts, making it more malleable. Follows the builder pattern.
 - Templated on scheme
 - Different default values based on scheme
 - Tests can be found in `TestContext.cpp`

2020-10-08 16:43 UTC, esteffin requested changes
Many changes and suggestions inputted.

I also suggest to change the `examples` programs to reflect the use of this new `ContextBuilder`. Same, but not so urgent, for `utils`.

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +   * @brief Sets `mvec` the unique primes which are factors of `m`.
```suggestion
   * @brief Sets `mvec`: the unique primes which are factors of `m`.
```

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +   * @note This is currently only enabled for the BGV scheme.
```suggestion
   * @note Only exists when the `Scheme` is `BGV`.
```

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +  ContextBuilder& mvec(NTL::Vec<long> mvec)
Can we make this method templated on the container type, so we can stop using `NTL::Vec` and use `std::vector` instead (then use `convert` inside the method)?

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +  ContextBuilder& mvec(NTL::Vec<long> mvec)
```suggestion
  ContextBuilder& mvec(const NTL::Vec<long>& mvec)
```
Pass by const ref or use `std::move` inside

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +   * @brief Toggle boostrapping will be `thin`.
This is not a toggle. It just sets thick to `false`

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +   * @note This is currently only enabled for the BGV scheme.
```suggestion
   * @note Only exists when the `Scheme` is `BGV`.
```

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +   * @note This is currently only enabled for the BGV scheme.
```suggestion
   * @note Only exists when the `Scheme` is `BGV`.
```

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +   * @brief Toggle boostrapping will be `thick`.
This is not a toggle. It just sets thick to false

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +   * @note This is currently only enabled for the BGV scheme.
```suggestion
   * @note @note Only exists when the `Scheme` is `BGV`.
```

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +   * @note This is currently only enabled for the BGV scheme.
Add what is the default for this flag

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +   * @note This is currently only enabled for the BGV scheme.
```suggestion
   * @note Only exists when the `Scheme` is `BGV`.
```

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +   **/
Add that for having the context bootstrappable `mvec` needs to be set properly

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +    if (buildModChainFlag_) {
I suggest to refactor the `context` creation statement out of the `if` condition to avoid code duplication.

I also suggest to use return-oriented programming, so having:
```
Context context(m_, p_, r_, gens_, ords_);
if (! buildModChainFlag_) 
  return context;
// Not the builder's setter method.
::helib::buildModChain(context, bits_, c_, bootstrappableFlag_);
if (!bootstrappableFlag_) 
    return context;
context.makeBootstrappable(mvec_);
return context;
```

2020-10-08 16:43 UTC, esteffin commented on include/helib/scheme.h
> +
If we don't want `SlotType` to be exposed, we can just forward-declare them

2020-10-08 16:43 UTC, esteffin commented on src/Context.cpp
> +std::ostream& operator<<<BGV>(std::ostream& os, const ContextBuilder<BGV>& cb)
Make this consistent with the other stream operators, so use json-like syntax (as `Ptxt`)

2020-10-08 16:43 UTC, esteffin commented on src/Context.cpp
> +std::ostream& operator<<<CKKS>(std::ostream& os, const ContextBuilder<CKKS>& cb)
Make this consistent with the other stream operators, so use json-like syntax (as `Ptxt`)

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +};
I strongly recommend to dene a `>>` operator to quickly deserialize a context builder from a file

2020-10-08 16:43 UTC, esteffin commented on include/helib/Context.h
> +// Default BGV values
I'm not sure Doxygen will not try to document this.
If it does, put a doxygen ignore or add a description

2020-10-08 16:43 UTC, esteffin commented on tests/TestContext.cpp
> +  EXPECT_GT(context->numPrimes(), 0);
Those checks have nothing to do with the test name.
But I'm not too passionated about this

2020-10-08 16:43 UTC, esteffin commented on tests/TestContext.cpp
> +  EXPECT_GT(context_built.numPrimes(), 0);
I don\t understand this test. Why the two `Context`s are equals after setting `gens` and `ords`?

2020-10-08 16:43 UTC, esteffin commented on tests/TestContext.cpp
> +                               .buildModChain(false)
Why is this ok? We expect the mod-chain to be built, but we set its flag to `false`...

2020-10-08 16:43 UTC, esteffin commented on tests/TestContext.cpp
> +TEST_P(TestContextBGV, contextBuilderBootstrappableContext)
Can we have a test where we check that we cannot have `bootstrappable = true` and `mvec` not set?

2020-10-08 16:43 UTC, esteffin commented on tests/TestContext.cpp
> +  EXPECT_GT(context_built.numPrimes(), 0);
Same as before, why are the two contexts equals?

2020-10-08 16:43 UTC, esteffin commented on tests/TestContext.cpp
> +                               .buildModChain(false)
Why `buildModChain` is false if we want it to be built?

2020-10-08 16:45 UTC, esteffin commented on tests/TestContext.cpp
I suggest to add a test for BGV and CKKS << operators

2020-10-08 18:21 UTC, esteffin commented
Put all implementation in a source file and then manually instantiate the two classes as done in `Ptxt.h, Ptxt.cpp`

2020-10-09 09:49 UTC, hamishun commented on include/helib/Context.h
> +template <typename SCHEME>
Or change the others to SCHEME. One convention is to scream type holders to not confuse them with actual defined types/classes.

2020-10-09 14:34 UTC, hamishun commented on include/helib/Context.h
> + * @brief `ostream` operator for serializing the `ContextBuilder` object.
```suggestion
 * @brief `ostream` operator for serializing the `ContextBuilder` object.
 * @tparam SCHEME The encryption scheme to be used, must be `BGV` or `CKKS`.
```

2020-10-09 14:35 UTC, hamishun commented on include/helib/Context.h
> + * @brief Builder to help construct a context.
```suggestion
 * @brief Builder to help construct a context.
 * @tparam SCHEME The encryption scheme to be used, must be `BGV` or `CKKS`.
```

2020-10-09 14:38 UTC, hamishun commented on include/helib/Context.h
> + **/
We should think what to add. Not to high priority as a blocker.

2020-10-09 14:39 UTC, hamishun commented on include/helib/Context.h
> +  long c_ = 2;
```suggestion
  long c_ = 3;
```

2020-10-09 14:51 UTC, hamishun commented on include/helib/Context.h
> +   **/
```suggestion
  /**
   * @brief Sets the bit size of the special primes in the modulus chain.
   * @param bits The bit size of the special primes in the modulus chain.
   * @return Reference to this `ContextBuilder` object.
   **/
```

2020-10-09 14:55 UTC, hamishun commented on include/helib/Context.h
> +   * @brief Toggle boostrapping will be `thin`.
```suggestion
   * @brief Sets boostrapping to be `thin`.
```

2020-10-09 14:55 UTC, hamishun commented on include/helib/Context.h
> +  bool thickFlag_ = true;
```suggestion
  bool thickFlag_ = false;
```

2020-10-09 14:59 UTC, hamishun commented on include/helib/Context.h
> +   * @brief Toggle boostrapping will be `thick`.
```suggestion
   * @brief Sets boostrapping to be `thick`.
```

2020-10-09 15:02 UTC, hamishun commented on include/helib/Context.h
> +    if (buildModChainFlag_) {
I think the bottom one looks more readable.

2020-10-09 15:08 UTC, hamishun commented on src/Context.cpp
> +Context& Context::operator=(Context&& other)
```suggestion

Context& Context::operator=(Context&& other)
```

2020-10-09 15:08 UTC, hamishun commented on src/Context.cpp
> +Context& Context::operator=(const Context& other)
```suggestion

Context& Context::operator=(const Context& other)
```

2020-10-09 15:08 UTC, hamishun commented on src/Context.cpp
> +Context::Context(Context&& other) :
```suggestion

Context::Context(Context&& other) :
```

2020-10-09 16:00 UTC, esteffin commented on src/Context.cpp
> +std::ostream& operator<<<CKKS>(std::ostream& os, const ContextBuilder<CKKS>& cb)
Done

2020-10-09 16:00 UTC, esteffin commented on src/Context.cpp
> +std::ostream& operator<<<BGV>(std::ostream& os, const ContextBuilder<BGV>& cb)
Done

2020-10-09 16:01 UTC, esteffin commented on include/helib/Context.h
> +   **/
Postponed to the future

2020-10-09 16:21 UTC, esteffin commented on include/helib/Context.h
> +   * @brief Toggle boostrapping will be `thin`.
Fixed

2020-10-09 16:21 UTC, esteffin commented on include/helib/Context.h
> +   * @brief Toggle boostrapping will be `thick`.
Done

2020-10-09 16:21 UTC, esteffin commented on include/helib/scheme.h
> +
We are not going to do this in this PR

2020-10-09 16:25 UTC, esteffin commented
> Put all implementation in a source file and then manually instantiate the two classes as done in `Ptxt.h, Ptxt.cpp`.
> 
> This will tidy up the code

Moved the `ContextBuilder` `build` method to `Context.cpp`.
The other setter methods are small enough, so are left into the header.

2020-10-09 16:25 UTC, esteffin commented on include/helib/Context.h
> +   * @param bits How many bit size of resolution.
Fixed

2020-10-12 09:12 UTC, hamishun commented on tests/TestContext.cpp
> +TEST_P(TestContextBGV, contextBuilderModChain)
```suggestion
TEST_P(TestContextBGV, contextBuilderNoModChain)
```

2020-10-12 09:12 UTC, hamishun commented on tests/TestContext.cpp
> +                               .buildModChain(false)
Test name is wrong. Changing now.

2020-10-12 09:16 UTC, hamishun commented on tests/TestContext.cpp
> +  EXPECT_GT(context->numPrimes(), 0);
It checks whether the context was built correctly. We should keep it.

2020-10-12 09:17 UTC, hamishun commented on tests/TestContext.cpp
> +  EXPECT_GT(context_built.numPrimes(), 0);
because `context` is the fixture context and it has those gens and ords.

2020-10-12 09:18 UTC, hamishun commented on tests/TestContext.cpp
> +TEST_P(TestContextBGV, contextBuilderBootstrappableContext)
Probably a good idea.

2020-10-12 09:19 UTC, hamishun commented on tests/TestContext.cpp
> +  EXPECT_GT(context_built.numPrimes(), 0);
because the test compares with the fixture `context`.

2020-10-12 09:23 UTC, esteffin commented on tests/TestContext.cpp
> +  EXPECT_GT(context->numPrimes(), 0);
Ok

2020-10-12 09:25 UTC, esteffin commented on tests/TestContext.cpp
> +  EXPECT_GT(context_built.numPrimes(), 0);
Ok.
Putting the context in the fixture is not super-straightforward as we don't have full control of what we are testing.
However we can keep how it is

2020-10-12 09:26 UTC, hamishun commented on tests/TestContext.cpp
> +                               .buildModChain(false)
Changing test name.

2020-10-12 09:27 UTC, hamishun commented on tests/TestContext.cpp
> +TEST_P(TestContextCKKS, contextBuilderModChain)
```suggestion
TEST_P(TestContextCKKS, contextBuilderNoModChain)
```

2020-10-12 09:45 UTC, hamishun commented on tests/TestContext.cpp
ok

2020-10-12 09:59 UTC, esteffin commented on include/helib/Context.h
> +};
Not for now

2020-10-12 11:10 UTC, esteffin commented on include/helib/Context.h
> +  ContextBuilder& mvec(NTL::Vec<long> mvec)
This will be addressed by a future PR

2020-10-12 11:11 UTC, esteffin commented on tests/TestContext.cpp
> +  EXPECT_GT(context_built.numPrimes(), 0);
Ok

2020-10-12 11:14 UTC, esteffin commented on tests/TestContext.cpp
> +                               .buildModChain(false)
Because `context` is the fixture `context` and it has those `gens` and `ords`.

2020-10-12 11:14 UTC, esteffin commented on tests/TestContext.cpp
Done

2020-10-12 11:15 UTC, esteffin commented on tests/TestContext.cpp
Done

2020-10-12 11:16 UTC, esteffin commented on tests/TestContext.cpp
> +  EXPECT_GT(context_built.numPrimes(), 0);
Ok

2020-10-12 11:19 UTC, esteffin approved these changes

2020-10-12 11:19 UTC, esteffin commented
Looks good to me

2020-10-12 12:53 UTC, merged