New bench
helibproject/HElib pull request #41
Opened 2020-11-10 17:03 UTC by jlhcrawford

- Updates documentation.
- Fixes existing performance tests.
- Introduces new performance tests.
- Introduces some common abstractions.
- Introduces fixes.

2020-11-11 09:42 UTC, esteffin commented
Jenkins run tests

2020-11-12 12:18 UTC, faberga commented on benchmarks/README.md
> +the project.
```suggestion
## Build benchmark

Benchmarks are found in `HElib/benchmarks` and are grouped by themes; the file
names reflect the themes they belong to.  By default, the benchmarks are built as 
separate executables. If you prefer to build a single executable then set the
`-DSINGLE_EXEC=ON`. Compiled tests appear in the `bin` directory.  Now build
the project.
```

2020-11-12 12:38 UTC, esteffin requested changes
Some minor changes,
Some major changes.

2020-11-12 12:38 UTC, esteffin commented on include/helib/Matrix.h
> +    return ret.inPlaceTranspose();
```suggestion
    ret.inPlaceTranspose();
    return ret;
```

This will enable RVO (if any)

2020-11-12 12:38 UTC, esteffin commented on benchmarks/ckks_common.h
> +    return (m != other.m || r != other.r || L != other.L) ? false : true;
```suggestion
    return m == other.m && r == other.r && L == other.L;
```

2020-11-12 12:38 UTC, esteffin commented on benchmarks/ckks_common.h
> +      secretKey((context.scale = 50,
Why `context.scale` have to be set here?
I suggest to use the builder pattern to set it correctly (if it is supported)
Or to set it after the context creation step (one line above)

Same for `buildModChain` below

2020-11-12 12:38 UTC, esteffin commented on benchmarks/ckks_common.h
> +      publicKey((secretKey.GenSecKey(),
Similarly to above, I suggest to do `secretKey.GenSecKey()` and `helib::addSome1DMatrices(secretKey)` where secret_key gets generated, to avoid errors

2020-11-12 12:38 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  meta.data->ea.random(v1);
This may fail if `meta.data` is `nullptr` (i.e. `meta` has not been initialized with the `operator()`)

2020-11-12 12:38 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  helib::Ctxt ctxt1(meta.data->publicKey), ctxt2(meta.data->publicKey);
```suggestion
  helib::Ctxt ctxt1(meta.data->publicKey);
  helib::Ctxt ctxt2(meta.data->publicKey);
```

2020-11-12 12:38 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  std::vector<long> v1, v2;
I suggest to change the `std::vector` to a `Ptxt` and then use `Ptxt::random` instead of creating the vector and then a Ptxt using it.

This will avoid copies of the vector and makes use of the random capability of the Ptxt object

2020-11-12 12:38 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  state.SetComplexityN(meta.data->params.m);
Is it ok that `SetComplexityN` uses `m` as parameter?

2020-11-12 12:38 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  std::vector<long> v1, v2;
As above I suggest to use `Ptxt` and `Ptxt::random` instead of passing to vectors

2020-11-12 12:38 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  helib::Ctxt ctxt1(meta.data->publicKey), ctxt2(meta.data->publicKey);
```suggestion
  helib::Ctxt ctxt1(meta.data->publicKey);
  helib::Ctxt ctxt2(meta.data->publicKey);
```

2020-11-12 12:38 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  std::cout << "Multiplications performed = " << state.iterations()
Why not `state.SetComplexityN(meta.data->params.m);` here?

2020-11-12 12:38 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  std::vector<long> vec;
Same as above. Use `Ptxt` directly

2020-11-12 12:38 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  std::vector<long> vec;
Use `Ptxt`

2020-11-12 12:38 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +
One thing we may do is to parametrize with a nice macro the number of steps 

```C++
#ifndef ITERATION_COUNT
  #define ITERATION_COUNT 200
#endif
```

In this way we may run the benchmarks on Jenkins compiling with `-DITERATION_COUNT=1` doing only one iteration

2020-11-12 12:38 UTC, esteffin commented on benchmarks/bgv_common.h
> +               : true;
```suggestion
    return m == other.m && p == other.p && r == other.r && L == other.L &&
           gens == other.gens && ords == other.ords;
```

2020-11-12 12:38 UTC, esteffin commented on benchmarks/bgv_common.h
> +                 helib::addSome1DMatrices(secretKey),
I suggest to put `helib::buildModChain(context, params.L, /*c=*/2)` on context creation and `secretKey.GenSecKey(), helib::addSome1DMatrices(secretKey)` on secret key creation

2020-11-12 12:38 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +  std::vector<std::complex<double>> vd1, vd2;
Use `Ptxt` object and `Ptxt::random`

2020-11-12 12:38 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +  state.SetComplexityN(meta.data->params.m);
As on BGV: `SetComplexityN` with `m`?

2020-11-12 12:38 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +  std::vector<std::complex<double>> vd1, vd2;
Use `Ptxt` and `Ptxt::random`

2020-11-12 12:38 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +  std::vector<std::complex<double>> vd;
Use `Ptxt` and `Ptxt::random`

2020-11-12 12:38 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +  std::vector<std::complex<double>> vd;
Use `Ptxt` and `Ptxt::random`

2020-11-12 12:38 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +  std::vector<std::complex<double>> vd1, vd2;
Use `Ptxt` and `Ptxt::random`

2020-11-12 12:38 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +
Same as for BGV. Why not using a macro for the iteration count?

2020-11-12 14:47 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  state.SetComplexityN(meta.data->params.m);
```suggestion
```

2020-11-12 14:48 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  std::cout << "Multiplications performed = " << state.iterations()
Not required

2020-11-12 14:49 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +
This will be addressed later

2020-11-12 14:52 UTC, esteffin commented on benchmarks/bgv_common.h
> +                 helib::addSome1DMatrices(secretKey),
This will be addressed in future releases as we refactor everything

2020-11-12 14:53 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +  state.SetComplexityN(meta.data->params.m);
```suggestion
```

Not required

2020-11-12 14:54 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +
This will be addressed in the future

2020-11-12 14:54 UTC, esteffin commented on benchmarks/ckks_common.h
> +      secretKey((context.scale = 50,
This will be addressed in future releases as we refactor everything

2020-11-12 14:54 UTC, esteffin commented on benchmarks/ckks_common.h
> +      publicKey((secretKey.GenSecKey(),
This will be addressed in future releases as we refactor everything

2020-11-12 14:56 UTC, esteffin commented on include/helib/Ptxt.h
> +  Ptxt(const PubKey& pk) : Ptxt(pk.getContext()){};
```suggestion
  explicit Ptxt(const PubKey& pk) : Ptxt(pk.getContext()){};
```

2020-11-12 14:58 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  meta.data->ea.random(v1);
Not true

2020-11-12 14:58 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  std::vector<long> v1, v2;
Done

2020-11-12 14:58 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  std::vector<long> vec;
Done

2020-11-12 14:58 UTC, esteffin commented on benchmarks/bgv_basic.cpp
> +  std::vector<long> vec;
Done

2020-11-12 14:58 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +  std::vector<std::complex<double>> vd1, vd2;
Done

2020-11-12 14:58 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +  std::vector<std::complex<double>> vd;
Done

2020-11-12 14:59 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +  std::vector<std::complex<double>> vd1, vd2;
Done

2020-11-12 14:59 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +  std::vector<std::complex<double>> vd;
Done

2020-11-12 14:59 UTC, esteffin commented on benchmarks/ckks_basic.cpp
> +  std::vector<std::complex<double>> vd1, vd2;
Done

2020-11-12 14:59 UTC, esteffin commented
Jenkins run tests

2020-11-12 15:00 UTC, esteffin approved these changes

2020-11-12 15:49 UTC, faberga approved these changes

2020-11-12 15:49 UTC, merged