CKKS Mitigation
helibproject/HElib pull request #43
Opened 2020-11-10 20:59 UTC by faberga

This implements the CKKS security mitigations.

2020-11-10 21:26 UTC, faberga commented
Jenkins run tests

2020-11-11 11:18 UTC, esteffin commented
Jenkins run tests

2020-11-11 11:35 UTC, esteffin commented
Jjenkins run tests

2020-11-11 11:35 UTC, esteffin commented
Jenkins run tests

2020-11-11 13:37 UTC, esteffin requested changes
@faberga and @esteffin  added many comments on this review phase.

@hamishun @jlhcrawford can you have a look at this?

2020-11-11 13:37 UTC, esteffin commented on include/helib/EncryptedArray.h
>     */
```suggestion
   * @param prec Unused.
   */
  // TODO: document this better (especially the prec parameter)
```

2020-11-11 13:37 UTC, esteffin commented on include/helib/EncryptedArray.h
>     */
```suggestion
   * @param prec Unused.
   */
  // TODO: document this better (especially the prec parameter)
```

2020-11-11 13:37 UTC, esteffin commented on include/helib/EncryptedArray.h
>    void decrypt(const Ctxt& ctxt, const SecKey& sKey, Ptxt<Scheme>& ptxt) const
```suggestion
  void decrypt(const Ctxt& ctxt, const SecKey& sKey, Ptxt<Scheme>& ptxt, OptLong prec = OptLong()) const
```

2020-11-11 13:37 UTC, esteffin commented on include/helib/EncryptedArray.h
>     * Decrypt a `Ctxt` ciphertext object to a `Ptxt` plaintext one relative to
```suggestion
   * @param prec `CKKS` precision to be used (must be defaulted if Scheme is `BGV`).
   * Decrypt a `Ctxt` ciphertext object to a `Ptxt` plaintext one relative to
```

2020-11-11 13:37 UTC, esteffin commented on include/helib/keys.h
>     * @param ciphertxt Ciphertext to decrypt.
```suggestion
   * @param ciphertxt Ciphertext to decrypt.
   * @param prec `CKKS` precision to be used (must be defaulted if Scheme is `BGV`).
```

2020-11-11 13:37 UTC, esteffin commented on include/helib/keys.h
>    template <typename Scheme>
```suggestion
  // TODO: document this better (especially the prec parameter)
  template <typename Scheme>
```

2020-11-11 13:37 UTC, esteffin commented on include/helib/EncryptedArray.h
>    template <typename Scheme>
```suggestion
  // TODO: document this better (especially the prec parameter)
  template <typename Scheme>
```

2020-11-11 13:37 UTC, esteffin commented on include/helib/keys.h
> +  // This just writes the derived part, not including the public key
Add a similar method for binary serialization
```suggestion
  // TODO: Add a similar method for binary serialization
  // This just writes the derived part, not including the public key
```

2020-11-11 13:37 UTC, esteffin commented on src/keys.cpp
> +#endif
```suggestion
    // TODO: Turn the following preprocessor logics into a warnOrThrow function
#ifdef HELIB_DEBUG
    Warning("noise bound exceeded in encryption");
#else
    throw LogicError("noise bound exceeded in encryption");
#endif
```
Turn the following preprocessor logics into a warnOrThrow function

2020-11-11 13:37 UTC, esteffin commented on src/keys.cpp
>  {
Should we check that `prec` is defaulted?

2020-11-11 13:37 UTC, esteffin commented on src/keys.cpp
> +  // assertEq(getContext(), ciphertxt.getContext(), "Context mismatch");
```suggestion
  // VJS-NOTE: why are we comapring contexts, rather
  // than addresses, which is what we do everywhere else?
  // I'm changing this for now...
  // assertEq(getContext(), ciphertxt.getContext(), "Context mismatch");
  // To be addressed later
```

2020-11-11 13:37 UTC, esteffin commented on src/Ctxt.cpp
> +  // derived from a  hash of sk and the ciphertext *this.
```suggestion
  // derived from a hash of sk and the ciphertext *this.
```

2020-11-11 15:51 UTC, faberga commented
Jenkins run tests

2020-11-11 17:59 UTC, faberga commented
Jenkins run tests

2020-11-11 22:32 UTC, faberga commented on include/helib/Context.h
> +  NTL::xdouble noiseBoundForGaussian(NTL::xdouble sigma, long degBound) const
Yes, documentation should be added as a separate PR

2020-11-11 22:43 UTC, faberga commented
Jenkins run tests

2020-11-11 23:19 UTC, faberga commented
Expected
`error: unused parameter ‘prec’ [-Werror=unused-parameter]`

```
/home/travis/build/helibproject/HElib/include/helib/EncryptedArray.h:1449:97: error: unused parameter ‘prec’ [-Werror=unused-parameter]
   void decrypt(const Ctxt& ctxt, const SecKey& sKey, Ptxt<Scheme>& ptxt, OptLong prec = OptLong()) const
```

**Fixes on the way.**

2020-11-11 23:37 UTC, faberga commented on include/helib/EncryptedArray.h
> +  // TODO: document this better (especially the prec parameter)
```suggestion
  // TODO: Complete the implementation to account for both 
  // CKKS and BGV, and document this better (especially the 
  // prec parameter)
```

2020-11-11 23:43 UTC, faberga commented on include/helib/EncryptedArray.h
> +  void decrypt(const Ctxt& ctxt, const SecKey& sKey, Ptxt<Scheme>& ptxt, OptLong prec = OptLong()) const
```suggestion
  void decrypt(const Ctxt& ctxt, const SecKey& sKey, Ptxt<Scheme>& ptxt) const
```

Removed `prec` parameter to avoid compilation error for now, until implementation is completed.

2020-11-11 23:58 UTC, esteffin commented
Jenkins run tests

2020-11-12 09:48 UTC, esteffin approved these changes

2020-11-12 10:05 UTC, merged