refactored added noise and added back isCorrect
helibproject/HElib pull request #54
Opened 2020-12-09 23:37 UTC by victorshoup

This implements the changes we discussed today. Basically, I changed the way the noise is added upon decryption.  This should be completely invisible to the user -- exactly the same amount of noise is added as before, except that now it takes place between "raw" decrypt and decode, rather than before "raw" decrypt.  I also added back the isCorrect method for Ctxt. It also now is implemented correctly to take into account the appropriate norm.

2020-12-15 15:18 UTC, hamishun commented on src/keys.cpp
> +bool isCorrect(const Ctxt& ctxt)
Just trying to understand. Why is this not a Ctxt method? It operates on a ctxt only.

2020-12-15 15:23 UTC, victorshoup commented on src/keys.cpp
> +bool isCorrect(const Ctxt& ctxt)
I wanted this function to be in keys.cpp, because its implementation depends on the constant DECRYPT_ON_PWFL_BASIS, which is also used in the implementation of Decrypt.  There is also a Ctxt method of the same name, but I felt it was uncool to implement such a method in keys.cpp.  So...pierced by the horns of this dilemma, I opted for the quirky solution of putting a free function in keys.cpp and the Ctxt method in Ctxt.cpp.

2020-12-16 11:57 UTC, esteffin requested changes
It seems that `private.h` has not been versioned.

Also I suggest to give a more explicative name than `private.h` as `internal_symbols.h` or similar.

2020-12-16 11:57 UTC, esteffin commented
jenkins run tests

2020-12-16 13:48 UTC, hamishun commented on include/helib/keys.h
> +
```suggestion
```

2020-12-16 14:33 UTC, esteffin approved these changes
Looks good to me

2020-12-17 10:42 UTC, merged