Travis-CI integration
helibproject/HElib pull request #9
Opened 2020-09-07 14:48 UTC by esteffin

First integration with Travis CI.

2020-09-07 19:38 UTC, faberga commented on .travis.yml
> +  - ./configure PREFIX=~/ntl SHARED=on NTL_GMP_LIP=on NTL_THREADS=on NTL_THREAD_BOOST=on GMP_PREFIX=/usr/
`GMP_Prefix=/usr/`  should not be required for the library install as NTL will look for it in the `/usr/` by default.

2020-09-07 19:50 UTC, faberga requested changes
See comments in the reviewed files

2020-09-07 19:50 UTC, faberga commented on .travis.yml
> +  - wget "https://www.shoup.net/ntl/ntl-11.4.3.tar.gz"
I would use `curl` instead of `wget`. 
it is easier in `curl` to avoid the issues we had with mismatching certificates when using htpps. Remember, we had this issue recently.  

`curl -k` does the trick.

`curl -o ntl-11.4.3.tar.gz https://www.shoup.net/ntl/ntl-11.4.3.tar.gz`

2020-09-07 19:50 UTC, faberga commented on .travis.yml
> +  - tar xf ntl-11.4.3.tar.gz
```suggestion
  - tar --no-same-owner -xf ntl-11.4.3.tar.gz
```

`--no-same-owner` is required to avoid a potential back door.

2020-09-07 19:50 UTC, faberga commented on README.md
> +[![Build Status](https://travis-ci.com/esteffin/HElib.svg?branch=master)](https://travis-ci.com/esteffin/HElib)
```suggestion
[![Build Status](https://travis-ci.com/helibproject/HElib.svg?branch=master)](https://travis-ci.com/helibproject/HElib)
```

this is one of the reasons I recommended doing this in the helibproject org.

2020-09-08 08:48 UTC, esteffin commented on .travis.yml
> +  - wget "https://www.shoup.net/ntl/ntl-11.4.3.tar.gz"
```suggestion
  - curl -O "https://www.shoup.net/ntl/ntl-11.4.3.tar.gz"
```

2020-09-08 08:48 UTC, esteffin commented on .travis.yml
> +  - ./configure PREFIX=~/ntl SHARED=on NTL_GMP_LIP=on NTL_THREADS=on NTL_THREAD_BOOST=on GMP_PREFIX=/usr/
```suggestion
  - ./configure PREFIX=~/ntl SHARED=on NTL_GMP_LIP=on NTL_THREADS=on NTL_THREAD_BOOST=on
```

2020-09-08 09:09 UTC, esteffin commented on .travis.yml
> +      - ctest -j2
```suggestion
      - ctest -j4
```

2020-09-08 11:15 UTC, faberga approved these changes
Approved.
requested changes applied and passed local tests

2020-09-08 11:23 UTC, merged